---
#
# Setting variables
################################################################################
- name: Loading the address to the most recent release of Zimbra OSE (8.7.11)
  set_fact: zmurl=https://files.zimbra.com/downloads/8.7.11_GA/

- name: Check if your distro is Ubuntu Server 16.04 LTS
  set_fact: zmpkg=zcs-8.7.11_GA_1854.UBUNTU14_64.20170531151956
  when: ansible_distribution_major_version|int >= 16

- name: Check if your distro is Ubuntu Server 14.04 LTS
  set_fact: zmpkg=zcs-8.7.11_GA_1854.UBUNTU14_64.20170531151956
  when: ansible_distribution_major_version|int >= 14 and ansible_distribution_major_version|int <= 15

- name: Check if your distro is Red Hat Enterprise Linux or CentOS (Major 6)
  set_fact: zmpkg=zcs-8.7.11_GA_1854.RHEL6_64.20170531151956
  when: ansible_distribution_major_version == "6"

- name: Check if your distro is Red Hat Enterprise Linux or CentOS (Major 7)
  set_fact: zmpkg=zcs-8.7.11_GA_1854.RHEL7_64.20170531151956
  when: ansible_distribution_major_version == "7"
