---
#
# Download and install Zimbra OSE
################################################################################
- name: Download and unpacking Zimbra OSE
  unarchive:
    validate_certs: no
    src: '{{ zmurl }}{{ zmpkg }}.tgz'
    dest: /usr/local/src/
    copy: no

- name: Create the folder to upload the scripts
  file:
    path: /tmp/zcs
    state: directory

- name: Uploading keystroke file
  template:
    src: 'installZimbra-keystrokes'
    dest: /tmp/zcs/installZimbra-keystrokes
    owner: root
    group: root
    mode: 0644

- name: Uploading installer configuration file
  template:
    src: 'installZimbraScript.j2'
    dest: /tmp/zcs/installZimbraScript
    owner: root
    group: root
    mode: 0644

- name: Installing Zimbra OSE
  shell: ./install.sh -s < /tmp/zcs/installZimbra-keystrokes
  args:
    chdir: '/usr/local/src/{{ zmpkg }}/'

- name: Configuring Zimbra OSE's services for use
  command: ./zmsetup.pl -c /tmp/zcs/installZimbraScript
  args:
    chdir: /opt/zimbra/libexec/

#
# BUGFIX WORKAROUND - Zimbra 8.8.5 does not work without configuring the hostname
################################################################################

- name: Configuring Zimbra Hostname for Domain {{ domain }}
  command: ./zmprov md {{ domain }} zimbraVirtualHostname {{ hostname }}.{{ domain }}
  args:
    chdir: /opt/zimbra/bin/

- name: Reloading Proxy configuration
  command: ./zmproxyconfgen
  args:
    chdir: /opt/zimbra/libexec/
