# This is the main file for the role.

#
# Loading variables
###################################
- include_vars: file='{{ ansible_os_family }}/packages.yml'
- include: 'vars/zimbra-{{ ansible_os_family }}.yml'

#
# Starting the install
###################################
- include: '{{ ansible_os_family }}/packages.yml'
- include: nodistro/install-zimbra.yml
- include: nodistro/install-spamassassin.yml
- include: nodistro/modify-logo.yml
  when: zmlogologin is defined and zmlogoapp is defined
- include: nodistro/policyd.yml

#
# Rebooting the Machine
###################################
- name: Rebooting the machine to apply the changes
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
