# This is the main file for the role.

#
# Loading variables
###################################
- include_vars: file='{{ ansible_os_family }}/packages.yml'
- include: 'vars/zimbra-{{ ansible_os_family }}.yml'

#
# Starting the install
###################################
- include: '{{ ansible_os_family }}/packages.yml'
- include: nodistro/install-zimbra.yml
- include: nodistro/install-spamassassin.yml
- include: nodistro/modify-logo.yml
  when: zmlogologin is defined and zmlogoapp is defined
- include: nodistro/policyd.yml
  notify: reboot-machine
