# Here we will download some packages that are needed to be present during the
# Zimbra install

- name: Download all the Zimbra's dependency for CentOS/RHEL System
  apt: pkg='{{ dependency }}' state=installed

- name: Ensure Postfix/dnsmasq not installed
  apt: pkg='{{ absent }}' state=absent
