# FILE: install-zimbra
# AUTHOR: Lucas Costa Beyeler
# E-MAIL: lucas.costab@outlook.com
# LAST CHANGE: 15/02/2017
#
# Playbook file to install and activate the PolicyD service in the Open Source Edition.
# PLEASE - If you made a change here, remember to do in a way that every distro
#          can use this change. Otherwise, please use the folder RedHat/Debian.

- name: Installing and Enabling the PolicyD Service
  shell: ./zmprov ms `zmhostname` +zimbraServiceInstalled cbpolicyd +zimbraServiceEnabled cbpolicyd
  args:
    chdir: /opt/zimbra/bin/

- name: Configuring PolicyD Database
  copy:
    src: 'config.php'
    dest: /opt/zimbra/common/share/webui/includes/config.php
    owner: root
    group: root
    mode: 0644

- name: Configuring PolicyD Web Interface
  file:
    src: /opt/zimbra/common/share/webui
    dest: /opt/zimbra/data/httpd/htdocs/webui
    state: link
