---
#
# Configuring Zimbra OSE
################################################################################
- name: Enabling Zimbra's admin through Proxy Server
  command: ./zmproxyconfig -e -w -C -H {{ hostname }}.{{ domain }}
  args:
    chdir: /opt/zimbra/libexec/
  become: yes
  become_user: zimbra

- name: Enabling HTTP to HTTPS redirect
  command: ./zmprov ms {{ hostname }}.{{ domain }} zimbraReverseProxyMailMode redirect
  args:
    chdir: /opt/zimbra/bin/
